# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: test mininet
        run: |
                git clone --depth=50 --branch=master https://github.com/mininet/mininet.git mininet/mininet
                cd mininet/mininet
                git checkout -qf bfc42f6d0
                sudo apt-get update -qq
                sudo apt-get install -qq vlan
                PYTHON=`which python` util/install.sh -n
                bash -c "if [ `lsb_release -rs` == '14.04' ]; then make codecheck; fi"
                pip install pexpect || pip3 install pexpect
                util/install.sh -nfvw
                alias sudo="sudo env PATH=$PATH"
                export PYTHON=`which python`
                echo 'px import sys; print(sys.version_info)' | sudo $PYTHON bin/mn -v output
                sudo $PYTHON bin/mn --test pingall
                sudo $PYTHON mininet/test/runner.py -v -quick
                sudo $PYTHON examples/test/runner.py -v -quick
