name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build dockerfile
        run: make reckon

      # ---- Tests ----
      - name: Client runner tests
        timeout-minutes: 1
        if: always()
        run: >
          docker run --env SHELL=/bin/bash --privileged -e DISPLAY --rm 
          --tmpfs /data 
          --network host --name reckon-test 
          cjen1/reckon:latest 
          python -c 'import reckon.client_test as c; c.test_client_runner()'

      - name: Test client=go
        timeout-minutes: 5
        if: always()
        run: >
          docker run --env SHELL=/bin/bash --privileged -e DISPLAY --rm 
          --tmpfs /data 
          --network host --name reckon-test 
          cjen1/reckon:latest 
          python -m reckon etcd --client go simple uniform none 

      - name: Test client=go-tracer
        timeout-minutes: 5
        if: always()
        run: >
          docker run --env SHELL=/bin/bash --privileged -e DISPLAY --rm 
          --tmpfs /data 
          --network host --name reckon-test 
          cjen1/reckon:latest 
          python -m reckon etcd --client go-tracer simple uniform none 

      - name: Test topo=simple
        timeout-minutes: 5
        if: always()
        run: >
          docker run --env SHELL=/bin/bash --privileged -e DISPLAY --rm 
          --tmpfs /data 
          --network host --name reckon-test 
          cjen1/reckon:latest 
          python -m reckon etcd --client go simple uniform none --number-nodes=5 --number-clients=2 --link-latency=100ms --link-loss=0.1

      - name: Test topo=wan
        timeout-minutes: 5
        if: always()
        run: >
          docker run --env SHELL=/bin/bash --privileged -e DISPLAY --rm 
          --tmpfs /data 
          --network host --name reckon-test 
          cjen1/reckon:latest 
          python -m reckon etcd --client go wan uniform none --number-nodes=5 --link-latency=100ms

      - name: Test failure=none
        timeout-minutes: 5 
        if: always()
        run: >
          docker run --env SHELL=/bin/bash --privileged -e DISPLAY --rm 
          --tmpfs /data 
          --network host --name reckon-test 
          cjen1/reckon:latest 
          python -m reckon etcd --client go wan uniform none

      - name: Test failure=leader
        timeout-minutes: 5 
        if: always()
        run: >
          docker run --env SHELL=/bin/bash --privileged -e DISPLAY --rm 
          --tmpfs /data 
          --network host --name reckon-test 
          cjen1/reckon:latest 
          python -m reckon etcd --client go wan uniform leader

      - name: Test failure=partial-partition
        timeout-minutes: 5 
        if: always()
        run: >
          docker run --env SHELL=/bin/bash --privileged -e DISPLAY --rm 
          --tmpfs /data 
          --network host --name reckon-test 
          cjen1/reckon:latest 
          python -m reckon etcd --client go wan uniform partial-partition

      - name: Test failure=intermittent-partial
        timeout-minutes: 5 
        if: always()
        run: >
          docker run --env SHELL=/bin/bash --privileged -e DISPLAY --rm 
          --tmpfs /data 
          --network host --name reckon-test 
          cjen1/reckon:latest 
          python -m reckon etcd --client go wan uniform intermittent-partial --mtbf=10

      - name: Test failure=intermittent-full
        timeout-minutes: 5 
        if: always()
        run: >
          docker run --env SHELL=/bin/bash --privileged -e DISPLAY --rm 
          --tmpfs /data 
          --network host --name reckon-test 
          cjen1/reckon:latest 
          python -m reckon etcd --client go wan uniform intermittent-full --mtbf=10

      - name: Test failure=kill-n
        timeout-minutes: 5 
        if: always()
        run: >
          docker run --env SHELL=/bin/bash --privileged -e DISPLAY --rm 
          --tmpfs /data 
          --network host --name reckon-test 
          cjen1/reckon:latest 
          python -m reckon etcd --client go wan uniform kill-n --kill-n 1
